# split panes using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v

# switch panes with alt + vim motion
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D
